### ISSUE TITLE
Twitter account login : error code 32

### ISSUE THREAD

**Issue by Aeris1One** [inovector/MixpostApp#5]
When trying to add a Twitter/X account, I get a 500 error. Twitter API keys are correct. Mastodon login works.

Debug enabled, here's the output : 
https://flareapp.io/share/w5B9DMg7

`/storage/logs/laravel.log` extract : 
```
[2023-11-26 19:47:37] production.ERROR: {"errors":[{"code":32,"message":"Could not authenticate you."}]} {"userId":1,"exception":"[object] (Abraham\\TwitterOAuth\\TwitterOAuthException(code: 0): {\"errors\":[{\"code\":32,\"message\":\"Could not authenticate you.\"}]} at /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/abraham/twitteroauth/src/TwitterOAuth.php:183)
[stacktrace]
#0 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/inovector/mixpost/src/SocialProviders/Twitter/Concerns/ManagesOAuth.php(9): Abraham\\TwitterOAuth\\TwitterOAuth->oauth()
#1 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/inovector/mixpost/src/Http/Controllers/AddAccountController.php(18): Inovector\\Mixpost\\SocialProviders\\Twitter\\TwitterProvider->getAuthUrl()
#2 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Inovector\\Mixpost\\Http\\Controllers\\AddAccountController->__invoke()
#3 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#4 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#7 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/inertiajs/inertia-laravel/src/Middleware.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inertia\\Middleware->handle()
#10 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/inovector/mixpost/src/Http/Middleware/Auth.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inovector\\Mixpost\\Http\\Middleware\\Auth->handle()
#12 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#16 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#18 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#20 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#21 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#23 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#25 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#27 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#29 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#31 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#35 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#44 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#46 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#48 /home/bama0413/domains/xyz.altearn.social/mixpostapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /home/bama0413/domains/xyz.altearn.social/mixpostapp/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 
```

**Comment by lao9s** [comment]
@Aeris1One Check the Callback url

**Comment by lao9s** [comment]
@Aeris1One The doc: https://docs.inovector.com/books/integration-of-social-platforms/page/twitter#bkmrk-step-5%3A-app-permissi

**Comment by Aeris1One** [comment]
I triple checked it, it's the correct one `https://mydomain.com/mixpost/callback/twitter`, I even added `https://mydomain.com/callback/twitter`. Mastodon's callback url is `https://mydomain.com/mixpost/callback/mastodon` so I see no possibility of it not being `/mixpost/callback/twitter`
